### ISSUE TITLE
Additional json-schema support.

### ISSUE THREAD

**Issue by tlivings** [tlivings/enjoi#1]
General:
- ~~enum~~
- ~~allOf~~
- ~~anyOf~~
- oneOf
- not
- format

Also:
- patternProperties?
- additionalProperties?
- maxProperties?
- minProperties?

**Comment by gergelyke** [comment]
Any update on this?

**Comment by tlivings** [comment]
It's been back-burnered but about to prioritize.

**Comment by gergelyke** [comment]
Any updates? :)

**Comment by tlivings** [comment]
Actually I just pushed `anyOf` support but I have more to do.

**Comment by tlivings** [comment]
Also just pushed `allOf` support.

**Comment by gergelyke** [comment]
Wooooo, thanks a lot!

**Comment by opyate** [comment]
Please parse ```definitions``` instead of requiring me to break a schema up into [subschemas](https://github.com/tlivings/enjoi#sub-schemas).

**Comment by tlivings** [comment]
The sub schemas option is for external schema references. If you want to resolve these references and feed them to enjoi, you can do so with the help of https://www.npmjs.com/package/extrefs.

Local inline dereferencing is supported without the need to specify these sub schemas.

**Comment by opyate** [comment]
@tlivings  Ah, I do apologise - I tested with a schema which is clearly broken:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CategoryHierarchyWsDTO",
  "type": "object",
  "properties":
  {
    "totalNumber":
    {
      "type": "number"
    },
    "pageSize":
    {
      "type": "number"
    },
    "numberOfPages":
    {
      "type": "number"
    },
    "subcategories":
    {
      "type": "array",
      "items":
      {
        "$ref": "#/definitions/CategoryHierarchyWsDTO"
      }
    },
    "currentPage":
    {
      "type": "number"
    },
    "id":
    {
      "type": "string"
    },
    "lastModified":
    {
      "type": "string"
    },
    "name":
    {
      "type": "string"
    },
    "url":
    {
      "type": "string"
    }
  },
  "definitions":
  {
  
  }
}

```

**Comment by toboid** [comment]
Would you accept a pull request for `minProperties` and `maxProperties` support?

**Comment by tlivings** [comment]
Of course.

**Comment by toboid** [comment]
[Looks](https://github.com/tlivings/enjoi/issues/1) like `minProperties` and `maxProperties` are already supported and seem to be working great

**Comment by tlivings** [comment]
Ha - I must not have updated my issue :)
