### ISSUE TITLE
Can't pass abortEarly (or other options) down to joi via schema.validate

### ISSUE THREAD

**Issue by rochal** [tlivings/enjoi#13]
Hi,

Joi supports abortEarly flag to return only first error that occured when validating the schema. This is by default set to true. This can be passed to joi passed via:

```
Joi.validate({firstName: 'John', lastName: 'Doe', age: 45}, schema, { abortEarly: false } , function (error, value) {
    error && console.log(error);
});
```

When using schema.validate() we lose the option to pass in options down to Joi:

```
schema.validate({firstName: 'John', lastName: 'Doe', age: 45}, function (error, value) {
    error && console.log(error);
});
```

Without having to add Joi as dependency, is there a away for enjoi to pass options down to joi?

**Comment by tlivings** [comment]
Sorry for taking so long to respond. Will look into this!

**Comment by tlivings** [comment]
You should be able to still call `Joi.validate` and pass this returned schema and options.

**Comment by tlivings** [comment]
Closing this, since this simply returns the joi schema and if calling `validate` on schema directly (as opposed to `Joi.validate`) doesn't support options, it's because `Joi` does not.
