### ISSUE TITLE
Seeking advice for introducing support for additionalProperties.

### ISSUE THREAD

**Issue by jsdevel** [tlivings/enjoi#14]
@tlivings thanks again for `enjoi`!

On a project right now and we have a need for `additionalProperties`.  What would be your preferred way to see this implemented?

**Comment by jsdevel** [comment]
cc @byarger

**Comment by jsdevel** [comment]
@tlivings I took the liberty of proposing an approach in #15.  Let me know what you'd like me to change.

**Comment by tlivings** [comment]
Fixed in v2.2.2 using your branch fixes @jsdevel !
