### ISSUE TITLE
Nullable fields

### ISSUE THREAD

**Issue by cmawhorter** [tlivings/enjoi#25]
JSON schema seems to support nullable fields through an array of types.  e.g. `some_property: { type: 'string' }` nullable would be `some_property: { type: [ 'string', 'null' ] }`. 

The array is auto joined to 'string,null' and since no type exists this fails.  

Doing `Enjoiy(..., { types: { 'string,null': Joi.string().allow(null) } })` seems to be a workaround.

**Comment by tlivings** [comment]
Can you point out the reference to this in the spec? Happy to support it but couldn't find the reference to an array of types.

**Comment by tlivings** [comment]
Fixed in v2.2.3.
