### ISSUE TITLE
3.2.3 is not the same as master

### ISSUE THREAD

**Issue by morgs32** [tlivings/enjoi#48]
@tlivings I'm not sure how... but if you `yarn add enjoi` which pulls the latest (3.2.3) it is not the same `envoi.js` as on master...

**Comment by tlivings** [comment]
Can you provide a bit more detail? Is this causing an issue? In the referenced issue can you tell me how `allOf` is not validating properly?

**Comment by morgs32** [comment]
3.2.3 appears to be a version of `lib/enjoi.js` from before this [commit](https://github.com/tlivings/enjoi/commit/c2a66f70f1aa1589dcd94551d9d4df045ab820c2#diff-7016c924633b8d2716537704ed62c295)

To see for yourself:
Run `npm pack enjoi`
Which downloads the 3.2.3 package as tarball.
Then open it.
Then open `lib/enjoi.js`
Then look on line 348
```
class All extends Alternatives {
...
```

Is that sufficient? I'm not sure why you made the changes you did in your commit ^^ but the current version supports `allOf`, not the version with `class All extends Alternatives`.

**Comment by tlivings** [comment]
Wait... is the complaint that I have not yet published the latest master? Or that the current version is somehow broken?

I merged a PR some days ago and haven't had a chance to publish due to travel.

**Comment by morgs32** [comment]
Ha.
Yes, that was it. I hope it didn't sound as much like a complaint as a curiosity:
> @tlivings I'm not sure how... but if you yarn add enjoi which pulls the latest (3.2.3) it is not the same envoi.js as on master...

**Comment by tlivings** [comment]
I need one more tweak before publishing so it will be out soon!

Thanks for your patience.
