### ISSUE TITLE
Circular dependency issue in api.json

### ISSUE THREAD

**Issue by rohan04** [tlivings/enjoi#5]
Having an issue with running a swagger application.  The api.json has an object which within itself has an  array of the same objects. For example : 

"Box": {
   "id" : "boxid",
    "boxes": {
      "type" : "array",
      "items" : {
           $ref : "BOX";
         }
     }
}

This is causing the error 
enjoi/node_modules/joi/lib/any.js:65
    var obj = Object.create(Object.getPrototypeOf(this));
                     ^
RangeError: Maximum call stack size exceeded

**Comment by hilkeheremans** [comment]
I'm also experiencing this issue when using swaggerize-routes, which depends on enjoi and joi. Apparently, recursion inside swagger jsons will cause enjoi's resolve() function to enter into an infinite recursion, which of course quickly overloads the V8 call stack.

While this could probably be fixed fairly easily in enjoi, I suspect a new problem will present itself, this time in joi (hapijs/joi#379), which currently does not support validation on a recursive schema.

**Comment by jorisroling** [comment]
I had the same issue, and solved it by changing the $ref to "#/BOX". Does that help?

**Comment by tlivings** [comment]
This shouldn’t be an issue any longer and doesn’t really have anything to do with Joi anyway. Use something that handles circular references like the swagger-parser before passing to enjoi (modern versions of swaggerize donand therefore should be fixed).
