### ISSUE TITLE
Saving Joi schema

### ISSUE THREAD

**Issue by panKt** [tlivings/enjoi#50]
I have converted object using enjoi. How do I store it as file now?

```
const Enjoi       = require('enjoi')
const { convert } = require('json-to-json-schema')
const jsonSchema  = convert({ name:'Bob' })
const joiSchema   = Enjoi(jsonSchema)

// I want to store 'joiSchema' as file so that it would have content similar to this:
//
// const SCHEMA = Joi.object().keys({
//   name : Joi.string().required()
// })


```

**Comment by tlivings** [comment]
Joi schemas are JavaScript objects so there is no practical way to serialize/deserialize to strings.

You can use `describe` to stringify it to a useful debugging format but nothing that I know of for converting it to a literal as used by `compile`.
