### ISSUE TITLE
"additionalProperties" in "allOf" does not work

### ISSUE THREAD

**Issue by ozum** [tlivings/enjoi#59]
Hi,

When `additionalProperties` is used with `allOf`, it does not work.

## Sample Code

```js
const Joi = require("joi");
const Enjoi = require("enjoi");

const jsonSchema = {
  allOf: [
    {
      allOf: [
        {
          type: "object",
          additionalProperties: false,
          properties: {
            a: { type: "string" },
            b: { type: "string" },
          },
        },
        {
          type: "object",
          properties: {
            c: { type: "string" },
            d: { type: "string" },
          },
        },
      ],
    },
  ],
};

const jsonSchema2 = {
  type: "object",
  properties: {
    a: { type: "string" },
    b: { type: "string" },
  },
};

const result = Joi.validate({ z: "3" }, Enjoi.schema(jsonSchema), { abortEarly: false });
const result2 = Joi.validate({ z: "4" }, Enjoi.schema(jsonSchema2), { abortEarly: false });

console.log(result.error);
console.log(result2.error);
```

## Actual Result

`null`
`{ ValidationError: "z" is not allowed ...} `

## Expected Result

`{ ValidationError: "z" is not allowed ...} `
`{ ValidationError: "z" is not allowed ...} `

Kind Regards,

**Comment by tlivings** [comment]
This is probably going to be a documented limitation of how allOf will work with Joi. allOf is not a combination of the defined schemas, but rather a validation against all provided schemas. 

To allow this to work, `allOf` must always allow additional properties so that it may continue checking. 

With access to more of the job error API we could get more custom about avoiding this sort of decision making but for now it's probably harder. 

Will think through it some more.

**Comment by ozum** [comment]
Oh, I missed that. It seems also a limitation of JSON Schema too, and this exact example is given in doc's [combining schemas section](https://json-schema.org/understanding-json-schema/reference/combining.html#allof)

It may be added in next versions of JSON Schema...

>This shortcoming is perhaps one of the biggest surprises of the combining operations in JSON schema: it does not behave like inheritance in an object-oriented language. There are some proposals to address this in the next version of the JSON schema specification.

**Comment by ozum** [comment]
As a workaround, in my **particular case at hand**, I will try to add an optional preprocess step to convert `allOf` to non cascading schema. (They are not equivalent in as per JSON Schema spec, but equal for my needs)

From:
```js
{
  allOf: [
    {
      allOf: [
        {
          type: "object",
          properties: {
            a: { type: "string" },
            b: { type: "string" },
          },
        },
        {
          type: "object",
          properties: {
            c: { type: "string" },
            d: { type: "string" },
          },
        },
      ],
    },
  ],
};
```

to

```js
{
  type: "object",
  additionalProperties: false,
  properties: {
    a: { type: "string" },
    b: { type: "string" },
    c: { type: "string" },
    d: { type: "string" },
  },
},
```

**Comment by tlivings** [comment]
Cool, and thanks for the feedback!

I appreciate the issues - helps me get insight into things I missed.
