### ISSUE TITLE
Bug: oneOf type makes field required

### ISSUE THREAD

**Issue by maldimirov** [tlivings/enjoi#61]
**Current behavior:**
The `oneOf` type makes a field required.

**Proper behavior:**
The `oneOf` type should make no changes to the required state of the field.

**Explanation:**
The `oneOf` type is a variation of [subschema boolean logic](http://json-schema.org/latest/json-schema-validation.html#logic). It's difference to `anyOf` which works properly in `enjoi` is that an instance should match exactly one of the subschemas. If it matches two or more - validation fails. But this is only if the instance value is present. That is, if the field is `oneOf`, but is not included as a [`required` field](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.3) it should pass validation.

**Comment by vbuch** [comment]
Actually the unit tests for oneOf are quite limited and do not cover all the scenarios. I recommend you prove your rightfulness by writing good tests.
