### ISSUE TITLE
Allowing empty strings by default for string types

### ISSUE THREAD

**Issue by maldimirov** [tlivings/enjoi#73]
The [`regularString` method](https://github.com/tlivings/enjoi/blob/master/lib/resolver.js#L355) makes, by default, an empty string a valid value for almost all string formats. This is a bug, since an empty string is not a valid value for e.g. an `ipv4` string (which by the JSON Schema spec should be in "dotted quad" format as per [RFC 2673](https://tools.ietf.org/html/rfc2673)).

Seems like the original reasoning behind this is that by default `joi` marks an empty string as an invalid value for any string type schema. But as I pointed out this breaks the logic for most string formats.

**Comment by tlivings** [comment]
Yeah I think there was a bug around the way joi handled this.

**Comment by maldimirov** [comment]
It isn't an issue with `joi` itself. It's [this line](https://github.com/tlivings/enjoi/blob/master/lib/resolver.js#L363) in the resolver code. Some string formats don't `return` in [the switch](https://github.com/tlivings/enjoi/blob/master/lib/resolver.js#L318), but `break` and go to the `regularString` function, which sets `''` as a valid value.

**Comment by yosheeck** [comment]
This is not fixed yet. Empty string still passes regex validation. 
So empty string of '' passes validation against regex of /theText/ which shouldn't be the case I think ?
I proposed a PR to fix it...

**Comment by svrnwnsch** [comment]
Hey, how is it possible to get the old behavior back which also allows empty strings?

**Comment by svrnwnsch** [comment]
Ah I see setting `minLength: 0` in the json schema works.

**Comment by iudex-** [comment]
Although @svrnwnsch is correct that setting `minLength: 0` fixes the issue, not accepting empty string for the string type directly contradicts the [JSON schema specification](https://json-schema.org/understanding-json-schema/reference/string.html) (as well as the [openapi spec](https://swagger.io/docs/specification/data-models/data-types/#string)).

I can see the point of not accepting empty strings if a format (optional part of the JSON schema spec) is set, but could the behavior of v6.0.0 of accepting empty string be restored for strings without formats?
