### ISSUE TITLE
joi and hoek deprecated, moved to @hapi/joi @hapi/hoek

### ISSUE THREAD

**Issue by nfstein** [tlivings/enjoi#76]
joi and hoek have been deprecated appear to have migrated to @hapi/joi and @hapi/hoek. Didn't see anything about this on the board so I'm posting it here. Did a quick swap out of the import statements and ran npm test which came back clean. Let me know if this has been addressed or you don't want to support the latest joi and hoek. Our security scanning software flagged hoek as having known vulnerabilities already, I'm not sure how valid that is, the software is not great, but we have to move away from enjoi if this isn't changed regardless. Have a nice day. PR here: https://github.com/tlivings/enjoi/pull/75

https://www.npmjs.com/package/joi
https://www.npmjs.com/package/hoek

ps I opened an issue for this earlier and it seems to have dissappeared so there might be a duplicate floating around

**Comment by tlivings** [comment]
Fixed in 6.0.0
