### ISSUE TITLE
Joi dependency in wrong section

### ISSUE THREAD

**Issue by travishorn** [tlivings/enjoi#78]
@hapi/joi is being used in the main code file `index.js` and therefor should be listed as a dependency instead of a devDependency.

The issue particularly affects you when you are already using the latest version of @hapi/joi in a project. The latest version has breaking changes to the version enjoi needs. Enjoi has no problem using the latest version you may have installed, instead of it's required version ^14. When enjoi tries to run `Joi.validate` a TypeError is thrown as that function has been removed.

**Comment by tlivings** [comment]
It’s listed as a `peerDependency` at the version it requires to run properly.

Will take it under consideration to make it a hard dependency.

**Comment by travishorn** [comment]
Ah, I see it as a peer dependency now. I missed the warning upon installing enjoi. Thanks.
