### ISSUE TITLE
Source code of version 6.0.0

### ISSUE THREAD

**Issue by rahulmohang** [tlivings/enjoi#86]
Hello all,

Can you please let me know where I can get the source code for version 6.0.0?

**Comment by tlivings** [comment]
Should be able to grab from commit history no?

**Comment by JoeScho** [comment]
Go to CHANGELOG.md > click on 'blame' > click on the commit next to v6.0.0 > click on "browse" and you can view the repo at that point in time

https://github.com/tlivings/enjoi/tree/acfebdb2de258655a22e1628c9a15c42388f55aa

**Comment by rahulmohang** [comment]
Thank you Trevor and Joe.

**Comment by rahulmohang** [comment]
Thank you @tlivings and @JoeScho.
