### ISSUE TITLE
Version 7.0.0 from npm still uses `@hapi/joi` instead `joi` library

### ISSUE THREAD

**Issue by svrnwnsch** [tlivings/enjoi#98]
I upgrade to latest version 7.0.0 But I still have conflicts that `node_modules/enjoi/index.js` links to `@hapi/joi` also the npm website still specifies @hapi/joi as a dev dependency 
![image](https://user-images.githubusercontent.com/1852828/95560640-d7728980-0a19-11eb-91a2-1a4c8f5dc833.png)

Am I doing something wrong? I already removed node modules and deleted yarn cache.
Or was there an older version released as 7.0.0 on npm?

**Comment by cjmFirefly03** [comment]
Looks like the latest version hasn't been published to npm. I noticed that as well.

**Comment by svrnwnsch** [comment]
My workaround currently is to pull from github instead of npm.
@tlivings how has the rights to push fixed version to npm?

**Comment by tlivings** [comment]
Published 8.0
